Fix case default arguments

diff --git a/scripts/build_server b/scripts/build_server
--- a/scripts/build_server
+++ b/scripts/build_server
@@ -35,7 +35,13 @@ while getopts ":s:h" opt; do
     tsan)
       server="dev"
       config="tsan";;
+    *)
+      echo "Invalid server: ${OPTARG}"
+      exit 1;;
     esac;;
+  *)
+    echo "Invalid argument: ${OPTARG}"
+    exit 1;;
   esac
 done
 
diff --git a/scripts/run_example b/scripts/run_example
--- a/scripts/run_example
+++ b/scripts/run_example
@@ -33,10 +33,13 @@ while getopts ":s:l:Ch" opt; do
     case "${OPTARG}" in
     asylo|dev|asan|tsan|none)
       server="${OPTARG}";;
-    \?)
+    *)
       echo "Invalid server: ${OPTARG}"
       exit 1;;
     esac;;
+  *)
+    echo "Invalid argument: ${OPTARG}"
+    exit 1;;
   esac
 done
 
diff --git a/scripts/run_examples b/scripts/run_examples
--- a/scripts/run_examples
+++ b/scripts/run_examples
@@ -20,10 +20,13 @@ while getopts ":s:h" opt; do
     case "${OPTARG}" in
     asylo|dev|asan|tsan)
       server="${OPTARG}";;
-    \?)
+    *)
       echo "Invalid server: ${OPTARG}"
       exit 1;;
     esac;;
+  *)
+    echo "Invalid argument: ${OPTARG}"
+    exit 1;;
   esac
 done
 
diff --git a/scripts/run_server b/scripts/run_server
--- a/scripts/run_server
+++ b/scripts/run_server
@@ -27,10 +27,13 @@ while getopts ":s:h" opt; do
     case "${OPTARG}" in
     asylo|dev|arm|asan|tsan)
       server="${OPTARG}";;
-    \?)
+    *)
       echo "Invalid server: ${OPTARG}"
       exit 1;;
     esac;;
+  *)
+    echo "Invalid argument: ${OPTARG}"
+    exit 1;;
   esac
 done
 
