Compile Docker server with clang (#930)
This change adds parameters for choosing server type in Docker images.
Change is necessary, since an Oak server for Docker images was not compiled using `clang`.

diff --git a/scripts/build_example b/scripts/build_example
--- a/scripts/build_example
+++ b/scripts/build_example
@@ -6,31 +6,42 @@ source "${SCRIPTS_DIR}/common"
 
 language="rust"
 compilation_mode='fastbuild'
-docker_image=false
-while getopts "l:ide:h" opt; do
+docker_config=''
+while getopts "e:l:di:h" opt; do
   case "${opt}" in
     h)
-      echo -e "Usage: ${0} [-h] [-l rust|cpp] [-i] [-d] -e EXAMPLE
+      echo -e "Usage: ${0} [-h] [-l rust|cpp] [-i base|logless] [-d] -e EXAMPLE
 
 Build the given example Oak Application and client.
 
 Options:
   -e    Example application name (required)
-  -i    Package application in a Docker image
-  -d    Build C++ code for example using debug mode
   -l    Example application variant:
           - rust (used by default)
           - cpp
+  -d    Build C++ code for example using debug mode
+  -i    This flag enables packaging the application into a Docker image,
+        and specifies the version of the Oak server, used by the application:
+          - base: base version of the server
+          - logless: base version of the server with debug logging compiled out
   -h    Print Help (this message) and exit"
       exit 0;;
-    l)
-      language="${OPTARG}";;
-    i)
-      docker_image=true;;
-    d)
-      compilation_mode='dbg';;
     e)
       readonly EXAMPLE="${OPTARG}";;
+    l)
+      language="${OPTARG}";;
+    d)
+      compilation_mode='dbg';;
+    i)
+      case "${OPTARG}" in
+        base)
+          docker_config='clang';;
+        logless)
+          docker_config='clang-logless';;
+        *)
+          echo "Invalid server type: ${OPTARG}"
+          exit 1;;
+      esac;;
     *)
       echo "Invalid argument: ${OPTARG}"
       exit 1;;
@@ -79,13 +90,13 @@ case "${language}" in
     exit 1;;
 esac
 
-if [[ "${docker_image}" == true ]]; then
+if [[ -n "${docker_config}" ]]; then
   if [[ "${language}" != "rust" ]]; then
     echo "Docker images are only supported for Rust modules"
     exit 1
   fi
 
-  bazel build "${bazel_build_flags[@]}" "//examples/${EXAMPLE}/server:${EXAMPLE}_image.tar"
+  bazel build "${bazel_build_flags[@]}" "--config=${docker_config}" "//examples/${EXAMPLE}/server:${EXAMPLE}_image.tar"
 
   # `aggregator` example has an additional Backend Docker image.
   if [[ "${EXAMPLE}" == "aggregator" ]]; then
