scripts: use consistent indentation
2 spaces, indented case arms, as per
https://google.github.io/styleguide/shellguide.html

diff --git a/scripts/build_server b/scripts/build_server
--- a/scripts/build_server
+++ b/scripts/build_server
@@ -8,7 +8,7 @@ server="asylo"
 config="enc-sim"
 while getopts "s:h" opt; do
   case "${opt}" in
-  h)
+    h)
       echo -e "Usage: ${0} [-s asylo|dev|arm|asan|tsan]
 
 Build the specified version of the Oak Runtime server.
@@ -21,35 +21,35 @@ Build the specified version of the Oak Runtime server.
           - tsan: 'dev' server with thread santizer
   -h    Print Help (this message) and exit"
       exit 0;;
-  s)
-    case "${OPTARG}" in
-    asylo)
-      server="asylo"
-      config="enc-sim";;
-    dev)
-      server="dev"
-      config="clang";;
-    arm)
-      server="dev"
-      config="armv8";;
-    asan)
-      server="dev"
-      config="asan";;
-    tsan)
-      server="dev"
-      config="tsan";;
+    s)
+      case "${OPTARG}" in
+        asylo)
+          server="asylo"
+          config="enc-sim";;
+        dev)
+          server="dev"
+          config="clang";;
+        arm)
+          server="dev"
+          config="armv8";;
+        asan)
+          server="dev"
+          config="asan";;
+        tsan)
+          server="dev"
+          config="tsan";;
+        *)
+          echo "Invalid server type: ${OPTARG}"
+          exit 1;;
+      esac;;
     *)
-      echo "Invalid server type: ${OPTARG}"
+      echo "Invalid argument: ${OPTARG}"
       exit 1;;
-    esac;;
-  *)
-    echo "Invalid argument: ${OPTARG}"
-    exit 1;;
   esac
 done
 
 bazel_build_flags+=(
-    "--config=${config}"
+  "--config=${config}"
 )
 
 if [[ "${server}" == "asylo" ]]; then
diff --git a/scripts/run_example b/scripts/run_example
--- a/scripts/run_example
+++ b/scripts/run_example
@@ -2,13 +2,13 @@
 
 readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
 # shellcheck source=scripts/common
-source "$SCRIPTS_DIR/common"
+source "${SCRIPTS_DIR}/common"
 
 language="rust"
 server="asylo"
 while getopts "s:l:e:h" opt; do
   case "${opt}" in
-  h)
+    h)
       echo -e "Usage: ${0} [-h] [-s asylo|dev|asan|tsan|none] [-l rust|cpp] -e EXAMPLE [-- CLIENT_ARGS]
 
 Build and run the given example Oak Application and client.
@@ -27,21 +27,21 @@ Options:
   -h    Print Help (this message) and exit
 Options after -- will be passed to the example client program."
       exit 0;;
-  l)
-    language="${OPTARG}";;
-  s)
-    case "${OPTARG}" in
-    asylo|dev|asan|tsan|none)
-      server="${OPTARG}";;
+    l)
+      language="${OPTARG}";;
+    s)
+      case "${OPTARG}" in
+        asylo|dev|asan|tsan|none)
+          server="${OPTARG}";;
+        *)
+          echo "Invalid server type: ${OPTARG}"
+          exit 1;;
+      esac;;
+    e)
+      readonly EXAMPLE="${OPTARG}";;
     *)
-      echo "Invalid server type: ${OPTARG}"
+      echo "Invalid argument: ${OPTARG}"
       exit 1;;
-    esac;;
-  e)
-    readonly EXAMPLE="${OPTARG}";;
-  *)
-    echo "Invalid argument: ${OPTARG}"
-    exit 1;;
   esac
 done
 shift "$((OPTIND -1))"
@@ -54,18 +54,18 @@ fi
 if [[ "${server}" != "none" ]]; then
   # Choose example application variant.
   case "${language}" in
-  rust)
-    readonly APPLICATION="${PWD}/bazel-client-bin/examples/${EXAMPLE}/config/config.bin";;
-  cpp)
-    # TensorFlow example is compiled with Emscripten and other examples with Clang.
-    if [[ "${EXAMPLE}" == "tensorflow" ]]; then
-      readonly APPLICATION="${PWD}/bazel-emscripten-bin/examples/tensorflow/config/config_cpp.bin"
-    else
-      readonly APPLICATION="${PWD}/bazel-wasm-bin/examples/${EXAMPLE}/config/config_cpp.bin"
-    fi;;
-  *)
-    echo "Invalid example variant: ${language}"
-    exit 1;;
+    rust)
+      readonly APPLICATION="${PWD}/bazel-client-bin/examples/${EXAMPLE}/config/config.bin";;
+    cpp)
+      # TensorFlow example is compiled with Emscripten and other examples with Clang.
+      if [[ "${EXAMPLE}" == "tensorflow" ]]; then
+        readonly APPLICATION="${PWD}/bazel-emscripten-bin/examples/tensorflow/config/config_cpp.bin"
+      else
+        readonly APPLICATION="${PWD}/bazel-wasm-bin/examples/${EXAMPLE}/config/config_cpp.bin"
+      fi;;
+    *)
+      echo "Invalid example variant: ${language}"
+      exit 1;;
   esac
   "${SCRIPTS_DIR}/build_example" -e "${EXAMPLE}"
 
diff --git a/scripts/run_examples b/scripts/run_examples
--- a/scripts/run_examples
+++ b/scripts/run_examples
@@ -7,7 +7,7 @@ source "${SCRIPTS_DIR}/common"
 server="asylo"
 while getopts "s:h" opt; do
   case "${opt}" in
-  h)
+    h)
       echo -e "Usage: ${0} [-s asylo|dev|asan|tsan]
   -s    Server type used to run exmples:
           - asylo: server based on the Asylo framework (used by default)
@@ -16,17 +16,17 @@ while getopts "s:h" opt; do
           - tsan: 'dev' server with thread santizer
   -h    Print Help (this message) and exit"
       exit 0;;
-  s)
-    case "${OPTARG}" in
-    asylo|dev|asan|tsan)
-      server="${OPTARG}";;
+    s)
+      case "${OPTARG}" in
+        asylo|dev|asan|tsan)
+          server="${OPTARG}";;
+        *)
+          echo "Invalid server type: ${OPTARG}"
+          exit 1;;
+      esac;;
     *)
-      echo "Invalid server type: ${OPTARG}"
+      echo "Invalid argument: ${OPTARG}"
       exit 1;;
-    esac;;
-  *)
-    echo "Invalid argument: ${OPTARG}"
-    exit 1;;
   esac
 done
 
diff --git a/scripts/run_server b/scripts/run_server
--- a/scripts/run_server
+++ b/scripts/run_server
@@ -7,7 +7,7 @@ source "${SCRIPTS_DIR}/common"
 server="asylo"
 while getopts "s:a:h" opt; do
   case "${opt}" in
-  h)
+    h)
       echo -e "Usage: ${0} [-s asylo|dev|arm|asan|tsan] -a APPLICATION
   -a    Path to a serialized application configuration file (required)
   -s    Server type:
@@ -18,19 +18,19 @@ while getopts "s:a:h" opt; do
           - tsan: 'dev' server with thread santizer
   -h    Print Help (this message) and exit"
       exit 0;;
-  s)
-    case "${OPTARG}" in
-    asylo|dev|arm|asan|tsan)
-      server="${OPTARG}";;
+    s)
+      case "${OPTARG}" in
+        asylo|dev|arm|asan|tsan)
+          server="${OPTARG}";;
+        *)
+          echo "Invalid server type: ${OPTARG}"
+          exit 1;;
+      esac;;
+    a)
+      readonly APPLICATION="${OPTARG}";;
     *)
-      echo "Invalid server type: ${OPTARG}"
+      echo "Invalid argument: ${OPTARG}"
       exit 1;;
-    esac;;
-  a)
-    readonly APPLICATION="${OPTARG}";;
-  *)
-    echo "Invalid argument: ${OPTARG}"
-    exit 1;;
   esac
 done
 
