Restore minimal macOS build support
This is mostly a revert of commit 5f95a10bb2ea ("builds: drop support
for MacOS (#940)"), but with conflicts resolved and scripts updated.

The main changes from a revert are:
 - Reorder sections in the docs/INSTALL-OSX.md doc to reflect the
   primacy of Rust.
 - Add an OS conditional clause to avoid using a musl build for the
   server binary, because musl is Linux-specific (it is built on the
   Linux syscall layer).
 - Fiddle with one of the checks in check_formatting to get it working
   on both macOS and Linux.

diff --git a/scripts/check_formatting b/scripts/check_formatting
--- a/scripts/check_formatting
+++ b/scripts/check_formatting
@@ -20,7 +20,7 @@ find . \
     \( -type f -name BUILD -or -name WORKSPACE -or -name '*.bzl' \) \
   \) -exec buildifier -lint=warn -mode=check {} +
 
-find . \
+readonly MISSING_LICENSES=$(find . \
   \(  \
     -not \( -path ./.git -prune \) -and \
     -not \( -path ./bazel-cache -prune \) -and \
@@ -29,7 +29,11 @@ find . \
     -not \( -path ./target -prune \) -and \
     -not \( -path ./third_party -prune \) \
     \( -type f -name BUILD \) \
-  \) -exec grep --files-without-match '^    licenses = \["notice"\],$' {} + && (echo 'missing license directive in BUILD file'; exit 1)
+  \) -exec grep --files-without-match '^    licenses = \["notice"\],$' {} +)
+if [[ -n "$MISSING_LICENSES" ]] ; then
+  echo "missing license directive in BUILD file(s): $MISSING_LICENSES"
+  exit 1
+fi
 
 # Check shell scripts for common mistakes.
 find scripts -type f -exec shellcheck {} +
