Use single app server in examples
This change refactors examples to use a single application server.

Fixes #462

diff --git a/scripts/run_examples_dev b/scripts/run_examples_dev
--- a/scripts/run_examples_dev
+++ b/scripts/run_examples_dev
@@ -2,20 +2,23 @@
 
 readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
 # shellcheck source=scripts/common
-source "$SCRIPTS_DIR/common"
+source "${SCRIPTS_DIR}/common"
 
 # Build Oak server.
-"$SCRIPTS_DIR/build_server_dev" "$@"
+"${SCRIPTS_DIR}/build_server_dev" "$@"
 
-# Run Oak server.
-./bazel-clang-bin/oak/server/dev/oak &
-SERVER_PID=$!
 # TODO: Ensure that background processes are killed with something like `trap cleanup_fn EXIT`.
 
 # Run Rust-based Oak examples against a common Oak server instance.
 # TODO(#594): Re-enable rustfmt when upstream rustc internal error is fixed.
 readonly RUST_EXAMPLES="$(find examples -mindepth 2 -maxdepth 4 -type d -regex '.*/module.*/rust$' | cut -d'/' -f2 | uniq | grep -v rustfmt)"
 for example in ${RUST_EXAMPLES}; do
+  # Running `build_example` to compile application configurations before running the server.
+  "${SCRIPTS_DIR}/build_example" "${example}"
+  ./bazel-clang-bin/oak/server/dev/dev_oak_runner \
+    --application="${PWD}/bazel-client-bin/examples/${example}/config/config.bin" &
+  rust_example_pid=$!
+  sleep 2  # Wait for an application to start.
   # Currently `chat` application starts an infinite loop, so `run_examples` just checks
   # if the module can be loaded correctly.
   if [[ "chat" == "${example}" ]]; then
@@ -23,25 +26,37 @@ for example in ${RUST_EXAMPLES}; do
   else
     "${SCRIPTS_DIR}/run_example" "${example}"
   fi
+  # TODO: Ensure that background processes are killed with something like `trap cleanup_fn EXIT`.
+  kill -s SIGTERM "${rust_example_pid}"
 done
 
 # Run C++-based Oak examples.
-# TODO: Run TensorFlow example when Emscripten imports will be fixed.
-# https://github.com/project-oak/oak/issues/439
-readonly CPP_EXAMPLES="$(find examples -mindepth 2 -maxdepth 4 -type d -regex '.*/module.*/cpp$' | cut -d'/' -f2 | grep -v tensorflow)"
+readonly CPP_EXAMPLES="$(find examples -mindepth 2 -maxdepth 4 -type d -regex '.*/module.*/cpp$' | cut -d'/' -f2 | uniq)"
+
 for example in ${CPP_EXAMPLES}; do
-  "${SCRIPTS_DIR}/run_example" -c "${example}"
+  "${SCRIPTS_DIR}/build_example" "${example}"
+  # TensorFlow example is compiled with Emscripten and other examples with Clang.
+  if [[ "tensorflow" == "${example}" ]]; then
+    ./bazel-clang-bin/oak/server/dev/dev_oak_runner \
+      --application="${PWD}/bazel-emscripten-bin/examples/${example}/config/config_cpp.bin" &
+  else
+    ./bazel-clang-bin/oak/server/dev/dev_oak_runner \
+      --application="${PWD}/bazel-wasm-bin/examples/${example}/config/config_cpp.bin" &
+  fi
+  cpp_example_pid=$!
+  sleep 2  # Wait for an application to start.
+  "${SCRIPTS_DIR}/run_example" "${example}"
+  kill -s SIGTERM "${cpp_example_pid}"
 done
 
 # Special case: run the hello_world example with:
 #  - a storage provider
 #  - a configured translator module.
+./bazel-clang-bin/oak/server/dev/dev_oak_runner \
+  --application="${PWD}/bazel-client-bin/examples/hello_world/config/config_translator.bin" &
+readonly storage_example_pid=$!
 ./bazel-clang-bin/oak/server/storage/storage_server &
-STORAGE_PID=$!
-./examples/hello_world/run -C \
-  --translator_module=./examples/target/wasm32-unknown-unknown/release/translator.wasm \
-  --storage_address=127.0.0.1:7867
-kill -s SIGTERM "$STORAGE_PID"
-
-# Terminate the server
-kill -s SIGTERM "$SERVER_PID"
+readonly storage_server_pid=$!
+sleep 2  # Wait for an application to start.
+"${SCRIPTS_DIR}/run_example" "hello_world"
+kill -s SIGTERM "${storage_server_pid}" "${storage_example_pid}"
