Improve shell checking/linting
* Move shellcheck config into .shellcheckrc
* Add requirements for {} around env var usage
* Add shfmt utilty and apply it with Google style

Change-Id: I08a11482d4884b805af4539cf0bbb0d46a6a6964

diff --git a/scripts/lint/add_bazel_license b/scripts/lint/add_bazel_license
--- a/scripts/lint/add_bazel_license
+++ b/scripts/lint/add_bazel_license
@@ -4,12 +4,12 @@ set -o nounset
 set -o pipefail
 
 for file in "$@"; do
-    if ! buildozer "add licenses notice" "$file:__pkg__"; then
-        result=$?
-        # exit code 3 = success, no changes made. Annoying.
-        if [[ "$?" != "3" && "$?" != "0" ]]; then
-            echo "ERROR: Failed to add license to $file ($result)"
-            exit $result
-        fi
+  if ! buildozer "add licenses notice" "${file}:__pkg__"; then
+    result=$?
+    # exit code 3 = success, no changes made. Annoying.
+    if [[ ${result} != "3" && ${result} != "0" ]]; then
+      echo "ERROR: Failed to add license to ${file} (${result})"
+      exit "${result}"
     fi
+  fi
 done
diff --git a/scripts/lint/add_source_license b/scripts/lint/add_source_license
--- a/scripts/lint/add_source_license
+++ b/scripts/lint/add_source_license
@@ -4,9 +4,8 @@ set -o nounset
 set -o pipefail
 
 for file in "$@"; do
-    if ! head -n 50 "$file" | grep "Apache License" > /dev/null
-    then
-        echo "ERROR: Missing Apache License in $file"
-        exit 1
-    fi
+  if ! head -n 50 "${file}" | grep "Apache License" >/dev/null; then
+    echo "ERROR: Missing Apache License in ${file}"
+    exit 1
+  fi
 done
diff --git a/scripts/lint/validate_todos b/scripts/lint/validate_todos
--- a/scripts/lint/validate_todos
+++ b/scripts/lint/validate_todos
@@ -6,10 +6,10 @@ set -o errexit
 readonly TODO_REGEX='(TODO\(#[0-9]+\)|TODO: .+ - [0-9A-Za-z]+)'
 
 for file in "$@"; do
-    while IFS= read -r line; do
-        if [[ $line =~ "TODO" ]] && ! [[ $line =~ $TODO_REGEX ]]; then
-            echo "ERROR: Invalid TODO format in $file: $line"
-            exit 1
-        fi
-    done < "$file"
+  while IFS= read -r line; do
+    if [[ ${line} =~ "TODO" ]] && ! [[ ${line} =~ ${TODO_REGEX} ]]; then
+      echo "ERROR: Invalid TODO format in ${file}: ${line}"
+      exit 1
+    fi
+  done <"${file}"
 done
diff --git a/scripts/test_buildconfigs b/scripts/test_buildconfigs
--- a/scripts/test_buildconfigs
+++ b/scripts/test_buildconfigs
@@ -15,7 +15,7 @@ export JUST_TIMESTAMP_FORMAT=JUST:%H:%M:%S%.3f
 
 failures=()
 
-check_buildconfig () {
+check_buildconfig() {
   buildconfig="$1"
 
   # shellcheck source=/dev/null
@@ -42,8 +42,7 @@ done
 failure_count="${#failures[@]}"
 echo ""
 echo ""
-for f in "${failures[@]}"
-do
-  echo "******Missing Output - $f"
+for f in "${failures[@]}"; do
+  echo "******Missing Output - ${f}"
 done
-exit "$failure_count"
+exit "${failure_count}"
